### ISSUE TITLE
Client log spam

### ISSUE THREAD

**Issue by G1ll0u** [fonnymunkey/FermiumASM#18]
Hello guys,

I'm spammed like this just after loading menu :

Log extract :
<details>
`[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: java.io.FileNotFoundException: minecraft:textures/mcpatcher/cit/items/armoricons/root_hood.png
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at mirror.normalasm.client.sprite.FramesTextureData.load(FramesTextureData.java:164)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at mirror.normalasm.client.sprite.FramesTextureData.size(FramesTextureData.java:126)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_110970_k(TextureAtlasSprite.java:349)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.block.model.ItemModelGenerator.func_178393_a(SourceFile:170)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.block.model.ItemModelGenerator.func_178397_a(SourceFile:67)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.block.model.ItemModelGenerator.func_178394_a(SourceFile:57)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.block.model.ItemModelGenerator.func_178392_a(SourceFile:37)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.CustomItemProperties.makeBakedModel(CustomItemProperties.java:880)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.CustomItemProperties.updateModelTexture(CustomItemProperties.java:829)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.CustomItems.updateModels(CustomItems.java:319)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:318)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.util.TextureUtils$1.func_110549_a(TextureUtils.java:362)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:366)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2818)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1312)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:8114)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: java.io.FileNotFoundException: minecraft:textures/mcpatcher/cit/items/armoricons/root_pants.png
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
[00:03:03] [Client thread/INFO] [STDERR]: [mirror.normalasm.client.sprite.FramesTextureData:load:167]: 	at mirror.normalasm.client.sprite.FramesTextureData.load(FramesTextureData.java:164)
Arrêt de la surveillance des logs du jeu car la longueur du journal dépassait 100000 lignes.`

</details>

Maybe it is just an optifine issue, my resource pack contains these missing PNGs.
I know I shoudn't use Optifine but me and my friends and I use shaders. I report it to you because I see normalasm mirror.normalasm.client.sprite.FramesTextureData:load :

It seems that it happens since I installed FermiumASM but I have to check.
My Entire log : (unable to fit in mclo.gs because of its 135000 lines)
https://kdrive.infomaniak.com/app/share/592874/5c08ee43-3ff9-4bca-ad5a-7d7bc8651d6c

Oh and just a question, is normalasm.cfg for your mod too ?
If yes, should I change this setting? :
![image](https://github.com/fonnymunkey/FermiumASM/assets/36129824/d40c6e2e-8716-4f0a-86ab-8a046396bbc7)

**Comment by fonnymunkey** [comment]
I don't see those errors from the extracted part in the log you provided, the log spam making that log giant is from Optifine complaining about issues with the shaders, which is likely because you are using Complimentary 5.2, which the 5.2 update added a lot related to newer version of MC/Optifine and Iris, and does not work properly with 1.12.2.
You should switch back to 5.1.1 or earlier versions of Complimentary.

FermiumASM does use normalasm.cfg for compatibility. You can turn that option off but the error logging is more likely caused by the texture being missing in general rather than that option.

If you are using a resourcepack to replace those textures, and your log doesn't have those errors, but your friends log does, you should ensure your friend actually has the resourcepack added and enabled.

**Comment by G1ll0u** [comment]
Yes I know for the shaders but a lot of this shader's features still work really good on our old optifine.

Here is my true log of 135000 lines that don't fit on mclo.gs : https://kdrive.infomaniak.com/app/share/592874/5c08ee43-3ff9-4bca-ad5a-7d7bc8651d6c
You can see that it's full of : mirror.normalasm.client.sprite.FramesTextureData

I forgot to mention that this spam takes approx 15sec and seems to block loading right before arriving to main menu. I just started the game without Fermium and the problem is gone and my loading was faster: [log](https://mclo.gs/i6tF6sa).
I'm now trying to get back to normalasm 5.6 and the game [crashes serverely with FATAL ERROR lol](https://mclo.gs/u2GUb9c)

No worries, I start the game again, it doesn't crashes but the problem is the same (log spam).

The game crashed like this surely because of my overclocking so don't worry about that.


Have a nice day

**Comment by G1ll0u** [comment]
Reported to official repo with more details.
https://github.com/LoliKingdom/LoliASM/issues/256
