### ISSUE TITLE
Cleanroom breaking hashmap

### ISSUE THREAD

**Issue by valiray** [fonnymunkey/FermiumASM#24]
this is just with the mods FermiumASM, FermiumBooter, fugue and scalar

![2024-11-30_17 19 45](https://github.com/user-attachments/assets/509ee3e6-3932-4e7f-8115-9ee7855d7ae8)
[full log](https://mclo.gs/xBTq639)

```
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: java.lang.ClassCastException: Cannot cast java.util.concurrent.ConcurrentHashMap to java.util.HashMap
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/java.lang.Class.cast(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at mirror.normalasm.common.java.JavaFixes.run(JavaFixes.java:47)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at mirror.normalasm.common.java.JavaFixes.onWorldLoad(JavaFixes.java:69)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_JavaFixes_onWorldLoad_Load.invoke(.dynamic)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:92)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:75)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:529)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1066)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4103)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[17:21:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)```

**Comment by fonnymunkey** [comment]
Disable "filePermissionsCacheCanonicalization" in the normalasm.cfg file.
Cleanroom has opted to only apply the fixes in Fugue for CleanroomLoader/Modern Java to CensoredASM but not NormalASM/FermiumASM so adding Fugue won't fix anything for these issues.

**Comment by valiray** [comment]
perfect, thanks for the help
