### ISSUE TITLE
NoClassDefFoundError: fermiumbooter/FermiumRegistryAPI

### ISSUE THREAD

**Issue by Ra2-IFV** [fonnymunkey/FermiumASM#26]
<details>
```
2024-12-07 15:35:57,218 main ERROR appender Console has no parameter that matches element Policies
[15:35:57] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by net.minecraftforge.fml.common.launcher.FMLTweaker (file:/minecraft/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860.jar)
WARNING: Please consider reporting this to the maintainers of net.minecraftforge.fml.common.launcher.FMLTweaker
WARNING: System::setSecurityManager will be removed in a future release
[15:35:57] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:35:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:35:57] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[15:35:57] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 17.0.8-internal, running on Mac OS X:aarch64:17.6.1, installed at /java-17-openjdk
[15:35:57] [main/INFO]: Searching /minecraft/mods for mods
[15:35:57] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [___MixinCompat-1.1-1.12.2___].jar
[15:35:57] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in fermiumasm-5.24.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:35:57] [main/WARN]: The coremod FermiumASM (mirror.normalasm.core.NormalLoadingPlugin) is not signed!
[15:35:57] [main/INFO]: [javax.script.ScriptEngineManager:reportException:-1]: ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider scala.tools.nsc.interpreter.IMain$Factory not found
2024-12-07 15:35:57,383 main ERROR appender Console has no parameter that matches element Policies
[15:35:57] [main/INFO]: FermiumASM is on the client-side.
[15:35:57] [main/INFO]: FermiumASM is preparing and loading in mixins
[15:35:57] [main/WARN]: Replacing CA Certs with an updated one...
[15:35:57] [main/INFO]: Initializing StacktraceDeobfuscator...
[15:35:57] [main/INFO]: Found MCP stable-39 method mappings: methods-stable_39.csv
[15:35:57] [main/INFO]: Initialized StacktraceDeobfuscator.
[15:35:57] [main/INFO]: Installing DeobfuscatingRewritePolicy...
[15:35:57] [main/INFO]: Installed DeobfuscatingRewritePolicy.
[15:35:57] [main/INFO]: FermiumASM enqueueing early mixins
[15:35:57] [main/ERROR]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) [launcher.jar:?]
Caused by: java.lang.NoClassDefFoundError: fermiumbooter/FermiumRegistryAPI
	at mirror.normalasm.core.NormalLoadingPlugin.<init>(NormalLoadingPlugin.java:99) ~[fermiumasm-5.24.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source) ~[?:?]
	at java.lang.Class.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: fermiumbooter.FermiumRegistryAPI
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at mirror.normalasm.core.NormalLoadingPlugin.<init>(NormalLoadingPlugin.java:99) ~[fermiumasm-5.24.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source) ~[?:?]
	at java.lang.Class.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 12 more
Caused by: java.lang.NullPointerException: Cannot read the array length because "transformedClass" is null
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at mirror.normalasm.core.NormalLoadingPlugin.<init>(NormalLoadingPlugin.java:99) ~[fermiumasm-5.24.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source) ~[?:?]
	at java.lang.Class.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 12 more
Error
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.base/java.lang.SecurityManager.checkExit(Unknown Source)
	at java.base/java.lang.Runtime.exit(Unknown Source)
	at java.base/java.lang.System.exit(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 7 more
```
</details>

Just found this stupid problem is caused by loading mods in alphabetical order. Renaming to `00-fermiumbooter.jar` and `10-FermiumASM.jar` fixes this.
Consider release mods with this naming syntax

**Comment by fonnymunkey** [comment]
What loader are you getting this issue on? FermiumASM and FermiumBooter are named a specific way to load properly on both normal loaders like through Curseforge, as well as Cleanroom Loader

**Comment by Ra2-IFV** [comment]
Forge

**Comment by fonnymunkey** [comment]
Ah I see, you're using Pojav launcher. It is likely Pojav handles mod loading ordering differently than the other loaders which causes this issue.
